Jcontributor branch
UTT-Connole/class-api-IT4200-2024-fall pull request #29
Opened 2024-09-03 16:16 UTC by jacevtb0419

2024-09-03 16:24 UTC, d00304484 approved these changes
looks good

2024-09-03 16:27 UTC, ChristianBass reviewed
You need to fix merge conflicts

2024-09-04 16:11 UTC, bubbomb requested changes

2024-09-04 16:11 UTC, bubbomb commented on README.md
> +=======
The merge text `<<<<<<<< HEAD` and `>>>>>>>> main` should be removed before this code is merged.

2024-09-04 17:33 UTC, LauraCoulome approved these changes

2024-09-06 17:16 UTC, merged